adiciona mais 5 sites de programação em nuvem
gabrielcmarinho/links-uteis pull request #100
Opened 2020-11-02 20:18 UTC by Nerd0000

2020-11-08 07:48 UTC, gabrielcmarinho requested changes

2020-11-08 07:48 UTC, gabrielcmarinho commented on LINKS.md
> +- [CodeAnywhere](https://codeanywhere.com) - Plataforma de codificação na nuvem
Você trocou * por - em toda categoria de IDE Cloud

2020-11-09 12:17 UTC, Nerd0000 commented
Eu tinha achado q ficou melhor, mas voltei o *

2020-11-21 02:32 UTC, gabrielcmarinho commented
Fica difícil para revisar o que mudou, visto que agora muitas linhas estão modificadas. Por este motivo, estou fechando esta PR.

2020-11-21 02:32 UTC, closed without merging