adiciona mais 4 ide's cloud
gabrielcmarinho/links-uteis pull request #103
Opened 2020-12-07 18:25 UTC by Nerd0000

2021-02-20 06:20 UTC, gabrielcmarinho commented
Olá, Alan!

Acredito que essas plataformas não sejam IDEs de fato. O que você acha?

2021-02-23 17:36 UTC, Nerd00F commented
Olá, Gabriel.

Acredito que sejam, pois tanto é possível escrever no editor, quanto compilar.

2021-02-24 10:54 UTC, Fabricio-Lopees commented
Olá, eu só venho informar que este email foi errado, meu nome não é
Gabriel, e sim Fabrício rsrsrs.
Resolvi avisar em caso de haver mensagens de importância para a pessoa.

On Tue, Feb 23, 2021 at 2:36 PM Alan Christian <notifications@github.com>
wrote:

> Olá, Gabriel.
>
> Acredito que sejam, pois tanto é possível escrever no editor, quanto
> compilar.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gabrielcmarinho/links-uteis/pull/103#issuecomment-784375813>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASPSDQHEEWPTLPFB4UYBOPTTAPRSTANCNFSM4UQ22XXA>
> .
>

2021-02-24 11:33 UTC, Fabricio-Lopees commented
Perdão kkkkk, só agora vi que é issue do GitHub.

On Tue, Feb 23, 2021 at 2:36 PM Alan Christian <notifications@github.com>
wrote:

> Olá, Gabriel.
>
> Acredito que sejam, pois tanto é possível escrever no editor, quanto
> compilar.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gabrielcmarinho/links-uteis/pull/103#issuecomment-784375813>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASPSDQHEEWPTLPFB4UYBOPTTAPRSTANCNFSM4UQ22XXA>
> .
>

2021-03-05 02:27 UTC, gabrielcmarinho commented
O único que de fato compila algo ali é o StackBlitz, todo resto só interpreta HTML e JavaScript em tempo de execução. Consegue corrigir isso e deixar somente o StackBlitz?

2021-03-05 02:53 UTC, gabrielcmarinho requested changes
Por gentileza, verifique se os links já existem no repositório antes de adicionar um novo.

2021-03-05 02:53 UTC, gabrielcmarinho commented on LINKS.md
> +* [Codepen](https://codepen.io) - Plataforma de codificação na nuvem
Link já adicionado como [ferramenta de desenvolvimento](https://github.com/gabrielcmarinho/links-uteis/blob/master/LINKS.md#-ferramentas-de-desenvolvimento).

2021-03-05 02:53 UTC, gabrielcmarinho commented on LINKS.md
> +* [Code Sandbox](https://codesandbox.io) - Plataforma de codificação na nuvem
Link já adicionado como [ferramenta de desenvolvimento](https://github.com/gabrielcmarinho/links-uteis/blob/master/LINKS.md#-ferramentas-de-desenvolvimento).

2021-03-08 18:30 UTC, Nerd00F commented
Feito

2021-03-08 21:52 UTC, gabrielcmarinho approved these changes

2021-03-08 21:52 UTC, merged

2021-03-08 21:53 UTC, gabrielcmarinho commented
Muito obrigado pela contribuição, @Nerd00F!