adiciona mais duas ferramentas de design
gabrielcmarinho/links-uteis pull request #104
Opened 2020-12-07 18:30 UTC by Nerd0000

2021-03-05 02:29 UTC, gabrielcmarinho requested changes

2021-03-05 02:29 UTC, gabrielcmarinho commented on LINKS.md
> +* [Colors lol](https://colors.lol) - Apresenta paletas de cores.
Consegue tirar esse ponto final da descrição do link (da linha 152 também)?

2021-03-08 18:19 UTC, Nerd00F commented on LINKS.md
> +* [Colors lol](https://colors.lol) - Apresenta paletas de cores.
Feito

2021-03-08 21:49 UTC, gabrielcmarinho requested changes

2021-03-08 21:49 UTC, gabrielcmarinho commented on LINKS.md
> +* [Colors lol](https://colors.lol) - Apresenta paletas de cores
```suggestion
* [Colors lol](https://colors.lol) - Repositório de paletas de cores
```

2021-03-08 21:49 UTC, gabrielcmarinho commented on LINKS.md
> +* [Coolors](https://coolors.co/) - Insipire-se. Este site possui diversas palhetas de cores e ainda permite que você monte a sua própria palheta
Diminuir tamanho da descrição.

2021-03-09 18:52 UTC, Nerd00F commented
Feito

2021-03-13 17:40 UTC, gabrielcmarinho commented
Novamente, muito obrigado pela contribuição, @Nerd00F!

2021-03-13 17:40 UTC, merged