adiciona mais 3 bancos de imagens, corrige um link
gabrielcmarinho/links-uteis pull request #105
Opened 2020-12-07 18:36 UTC by Nerd0000

2021-03-05 02:47 UTC, gabrielcmarinho requested changes

2021-03-05 02:47 UTC, gabrielcmarinho commented on LINKS.md
> +* [Diversidade](https://github.com/JulianaHelena5/BancoDeImagensComDiversidade) - Bancos de Imagens com Pessoas Diversas, maior acesso e representatividade.
Remover ponto final, ordenar alfabeticamente e diminuir tamanho de descrição do link. Mais informações sobre padronização do projeto, acessar o [guia de contribuição](https://github.com/gabrielcmarinho/links-uteis/blob/master/CONTRIBUTING.md).

2021-03-05 02:47 UTC, gabrielcmarinho commented on LINKS.md
> +* [Diversidade](https://github.com/JulianaHelena5/BancoDeImagensComDiversidade) - Bancos de Imagens com Pessoas Diversas, maior acesso e representatividade.
E tomar cuidado com letras maiúsculas, tendo uso restrito para substantivos próprios, siglas, símbolos, nomes de instituições e início de frases.

2021-03-08 18:28 UTC, Nerd00F commented
Feito

2021-03-08 21:51 UTC, gabrielcmarinho requested changes

2021-03-08 21:51 UTC, gabrielcmarinho commented on LINKS.md
> +* [Diversidade](https://github.com/JulianaHelena5/BancoDeImagensComDiversidade) - Imagens com pessoas diversas.
```suggestion
* [BancoDeImagensComDiversidade](https://github.com/JulianaHelena5/BancoDeImagensComDiversidade) - Banco de imagens com pessoas diversas
```

2021-03-09 18:53 UTC, Nerd00F commented
Feito

2021-03-13 17:42 UTC, gabrielcmarinho approved these changes

2021-03-13 17:42 UTC, merged