adiciona mais 4 bancos de icones
gabrielcmarinho/links-uteis pull request #106
Opened 2020-12-07 18:44 UTC by Nerd0000

2021-03-05 02:38 UTC, gabrielcmarinho requested changes
Algumas observações sobre essa nova adesão de links.

2021-03-05 02:38 UTC, gabrielcmarinho commented on LINKS.md
> +* [Flat Icons](https://www.flaticon.com) - Ícones gratuitos: PNG, SVG, EPS, PSD e BASE 64.
Retirar ponto final de descrição do link

2021-03-05 02:38 UTC, gabrielcmarinho commented on LINKS.md
> +* [RemixIcon](https://remixicon.com) - Banco de Ícones para uso gratuito
```suggestion
* [RemixIcon](https://remixicon.com) - Banco de ícones para uso gratuito
```

2021-03-05 02:38 UTC, gabrielcmarinho commented on LINKS.md
> +* [Material Design](https://material.io/resources/icons/?style=baseline) - Pacote de icones do google
Remover parâmetros do link. Mais informações sobre esses padrões no [guia de contribuição](https://github.com/gabrielcmarinho/links-uteis/blob/master/CONTRIBUTING.md).

2021-03-08 18:24 UTC, Nerd00F commented
Feito

2021-03-08 21:55 UTC, gabrielcmarinho requested changes

2021-03-08 21:55 UTC, gabrielcmarinho commented on LINKS.md
> +* [Material Design](https://material.io/resources/icons) - Pacote de icones do google
```suggestion
* [Material Design](https://material.io/resources/icons) - Pacote de ícones do Google
```

2021-03-08 21:55 UTC, gabrielcmarinho commented on LINKS.md
> +* [Iconfonts](https://icofont.com) - Mais de 2100 ícones gratuitos para incrementar seus designs criativos
Linha 217 e 218 duplicadas.

2021-03-13 17:47 UTC, gabrielcmarinho reviewed
Você consegue remover os links da categoria de [banco de imagens gratuitas](https://github.com/gabrielcmarinho/links-uteis/blob/master/LINKS.md#-banco-de-imagens-gratuitas)?

2021-03-13 17:47 UTC, gabrielcmarinho commented on LINKS.md
> +* [Flat Icons](https://www.flaticon.com) - Ícones gratuitos: PNG, SVG, EPS, PSD e BASE 64
Esse link já existe no repositório, mas está na categoria errada. Você consegue removê-lo?

2021-03-13 17:47 UTC, gabrielcmarinho commented on LINKS.md
> +* [RemixIcon](https://remixicon.com) - Banco de ícones para uso gratuito
Este link também já existe no repositório, mas está na categoria errada. Você também consegue removê-lo?

2021-03-14 22:10 UTC, closed without merging