Adiciona o Miro à seção de Gerenciamento de Projetos
gabrielcmarinho/links-uteis pull request #113
Opened 2021-01-14 03:04 UTC by vitor-san

Adicionei o Miro (https://miro.com/), que é um whiteboard colaborativo em real-time que pode ser usado de forma gratuita. É bem difundido atualmente e muitas pessoas utilizam, principalmente, para organizar processos de UX Design. Porém a ferramenta não se limita a isso, podendo organizar literalmente qualquer coisa (já que o usuário tem a liberdade de colocar o que quiser no whiteboard).

2021-03-05 02:35 UTC, gabrielcmarinho requested changes

2021-03-05 02:35 UTC, gabrielcmarinho commented on LINKS.md
> +* [Miro](https://miro.com/) - Quadro branco colaborativo e em tempo real. Utilize post-its (e muito mais) para organizar qualquer processo.
Como descrito no [guia de contribuição](https://github.com/gabrielcmarinho/links-uteis/blob/master/CONTRIBUTING.md), a descrição do link não pode finalizar com ponto final. Além disso, achei essa descrição um pouco longa, acho que isso já seria o suficiente:
```suggestion
* [Miro](https://miro.com/) - Quadro branco colaborativo e em tempo real
```

Só essas observações mesmo. Quando fizer as alterações, me pinga por aqui que aprovo ;)

2021-03-14 00:48 UTC, vitor-san commented on LINKS.md
> +* [Miro](https://miro.com/) - Quadro branco colaborativo e em tempo real. Utilize post-its (e muito mais) para organizar qualquer processo.
Ok. Obrigado pelos toques! :)

2021-03-14 00:53 UTC, vitor-san commented
@gabrielcmarinho vê se agora está de acordo.

2021-03-14 01:46 UTC, gabrielcmarinho commented
Incrível! Muito obrigado pela contribuição, @vitor-san! 😄

2021-03-14 01:46 UTC, merged