new: Adicionei o canal Universo Programado à lista de canais do Youtube
gabrielcmarinho/links-uteis pull request #123
Opened 2021-03-12 16:20 UTC by PedroSouza157998

É um canal que fala sobre o funcionamento da lógica por trás de uma IA

2021-03-14 22:16 UTC, gabrielcmarinho requested changes
Acho que essa descrição seria ideal.

2021-03-14 22:16 UTC, gabrielcmarinho commented on LINKS.md
> +* [Universo Programado](https://www.youtube.com/channel/UCf_kacKyoRRUP0nM3obzFbg) - O canal fala principalmente sobre a lógica por trás do desenvolvimento das IA
```suggestion
* [Universo Programado](https://www.youtube.com/channel/UCf_kacKyoRRUP0nM3obzFbg) - Canal sobre a lógica por trás do desenvolvimento das IA
```

2021-03-15 12:21 UTC, PedroSouza157998 commented
eu sou novo com o git, me enganei na hora de fazer o commit. desculpas.

2021-03-15 14:01 UTC, gabrielcmarinho commented
Hahahaha, sem problemas, @PedroSouza157998. Na verdade foi só uma observação na descrição do link, seus commits foram feitos corretamente.

2021-04-01 02:03 UTC, gabrielcmarinho commented
Acha que consegue alterar com a observação que citei ali em cima, @PedroSouza157998 ?

2021-04-01 12:47 UTC, closed without merging