Adicionei um link para o Git command explorer
gabrielcmarinho/links-uteis pull request #124
Opened 2021-03-15 00:55 UTC by caiocichetti

2021-03-15 00:56 UTC, caiocichetti commented on LINKS.md
> +* [Git Command Explorer](https://gitexplorer.com/) - Encontre os comandos certos que você precisa sem vasculhar a web
Certo

2021-03-21 17:13 UTC, gabrielcmarinho requested changes

2021-03-21 17:13 UTC, gabrielcmarinho commented on LINKS.md
> +* [Git Command Explorer](https://gitexplorer.com/) - Encontre os comandos certos que você precisa sem vasculhar a web
Puts, esse link já existe na categoria **estudos** e aparentemente, o ideal seria na categoria de **ferramentas de desenvolvimento**. Você consegue remover o antigo?

2021-03-21 17:25 UTC, caiocichetti commented on LINKS.md
> +* [Git Command Explorer](https://gitexplorer.com/) - Encontre os comandos certos que você precisa sem vasculhar a web
Desculopa não me atentei a esse detalhe vou remover!

2021-03-21 23:34 UTC, merged