Links R e RStudio adicionados
gabrielcmarinho/links-uteis pull request #133
Opened 2021-03-30 00:47 UTC by CarlosViniMSouza

Alterações feitas : 
1 - Adicionado link para a Linguagem R : https://cran.r-project.org/
2 - Adicionado link para a IDE RStudio : https://www.rstudio.com/products/rstudio/download/#download

2021-03-30 00:50 UTC, CarlosViniMSouza commented
Adicionei 2 links - Linguagem R e RStudio

2021-04-01 01:55 UTC, gabrielcmarinho commented on LINKS.md
> +* [R](https://cran.r-project.org/) - Voltada para Matemática, Estatística, Análise
```suggestion
* [R](https://cran.r-project.org/) - Linguagem de programação com foco em matemática, estatística, análise de dados, ciência de dados, aprendizagem de máquina e inteligência de negócios
```

2021-04-01 01:55 UTC, gabrielcmarinho commented on LINKS.md
> +- [� Índice](#-índice)
Não faz sentido ter um link do índice no índice 😂

2021-04-01 01:56 UTC, gabrielcmarinho requested changes
Fiz algumas observações, aguardo as alterações para dar prosseguimento ao merge na master.

2021-04-01 03:26 UTC, CarlosViniMSouza commented on LINKS.md
> +- [� Índice](#-índice)
Isso aí deve ter sido o meu editor de código, pois não tinha visto tal alteração

2021-04-01 04:24 UTC, CarlosViniMSouza commented
Gabriel, verifica se ainda tem algo errado por favor.

2021-04-07 04:53 UTC, gabrielcmarinho commented on LINKS.md
> +para a Linguagem R e sua variantes
```suggestion
para a Linguagem R e suas variantes
```

2021-04-07 04:55 UTC, gabrielcmarinho commented on LINKS.md
> +* [R](https://cran.r-project.org/) - Linguagem de programação com foco em matemática, estatística, análise de dados, ciência de dados, aprendizagem de máquina e inteligência de negócios
```suggestion
* [R](https://cran.r-project.org/) - Linguagem de programação com foco em matemática, estatística, ciência de dados e aprendizagem de máquina
```

2021-04-07 04:55 UTC, gabrielcmarinho approved these changes

2021-04-07 04:56 UTC, merged