new : adiciona ferramentas de frontend
gabrielcmarinho/links-uteis pull request #85
Opened 2020-09-29 12:11 UTC by Vivi3008

2020-09-29 13:23 UTC, gabrielcmarinho requested changes

2020-09-29 13:23 UTC, gabrielcmarinho commented on LINKS.md
> +* [ManyPixels](https://www.manypixels.co/gallery/) - Galeria de ilustrações com direito a edição de cores.
Remova o ponto final da descrição do link na linha 34 e 35.

2020-09-29 14:52 UTC, Vivi3008 commented
Feito @gabrielcmarinho ! ;)

2020-09-30 01:34 UTC, merged

2020-09-30 01:35 UTC, gabrielcmarinho commented
Muito obrigado pela contribuição, @Vivi3008! Amei os sites que você adicionou.